#ifndef EGAV_THEME_HEADER
#define EGAV_THEME_HEADER 

#define EGAV_TITLE_NAME                          wxT("EG ClamNet Antivirus")
#define EGAV_ADMIN_PANEL_TITLE				     wxT("EG ClamNet Antivirus(Administrator)")

#define EGAV_WINDOW_BORDER_STYLE                 wxFRAME_TOOL_WINDOW | wxMINIMIZE_BOX 
#define EGAV_HOME_WINDOW_BORDER_STYLE            wxCAPTION | wxCLOSE_BOX | wxMINIMIZE_BOX | wxTAB_TRAVERSAL
#define EGAV_DIALOG_BORDER_STYLE				 wxCAPTION | wxTAB_TRAVERSAL
#define EGAV_WINDOW_BACK_COLOR1                  wxColor(30,31,34)//wxColor(64,96,138)//wxColor(45, 125, 116)
#define EGAV_WINDOW_BACK_COLOR2                  wxColor(230, 230, 230)
#define EGAV_PANEL_BACK_COLOR                    wxColor(44, 45, 48)

#define EGAV_BUTTON_STYLE_NOBORDER               0 | wxBORDER_NONE 
#define EGAV_BUTTON_BACK_COLOR1                  wxColor(221, 194, 114)
#define EGAV_BUTTON_BACK_COLOR2                  wxColor(52, 53, 54)//wxColor(176, 198, 195)
#define EGAV_BUTTON_TEXT_COLOR1                  wxColor(200, 236, 234)
#define EGAV_BUTTON_TEXT_COLOR2                  wxColor(16, 28 , 28)
#define EGAV_BUTTON_SIZE_BIG                     wxSize(160, 30)
#define EGAV_BUTTON_SIZE_MID                     wxSize(135, 27)
#define EGAV_BUTTON_SIZE_MID_SMALL               wxSize(100, 25)
#define EGAV_BUTTON_SIZE_SMALL                   wxSize(50, 27)

#define EGAV_DEFAULT_MSGWIN_SIZE				 wxSize(300 ,200)

#define EGAV_TEXT_COLOR_WHITE                    wxColor(255,255,255)

#define EGAV_FONT_BIG_ROMAN_NORMAL_NORMAL         wxFont(24, wxFONTFAMILY_ROMAN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_TINY_SWISS_NORMAL_NORMAL        wxFont(9, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_TINY_SWISS_NORMAL_NORMAL1       wxFont(10, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_TINY_ROMAN_NORMAL_BOLD          wxFont(10, wxFONTFAMILY_ROMAN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD)
#define EGAV_FONT_SMALL_ROMAN_ITTALIC_NORMAL      wxFont(11, wxFONTFAMILY_ROMAN, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_SMALL_ROMAN_NORMAL_NORMAL       wxFont(11, wxFONTFAMILY_ROMAN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_SMALL_ROMAN_NORMAL_BOLD		  wxFont(11, wxFONTFAMILY_ROMAN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD)
#define EGAV_FONT_SMALL_SWISS_NORMAL_NORMAL       wxFont(11, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID_ROMAN_ITTALIC_NORMAL        wxFont(12, wxFONTFAMILY_ROMAN, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID_SWISS_NORMAL_NORMAL         wxFont(12, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID_SWISS_ITTALIC_NORMAL        wxFont(12, wxFONTFAMILY_SWISS, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID_SWISS_NORMAL_BOLD           wxFont(12, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD)
#define EGAV_FONT_MID_DECORATIVE_NORMAL           wxFont(12, wxFONTFAMILY_DECORATIVE, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID2_SWISS_NORMAL_NORMAL        wxFont(18, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID3_SWISS_NORMAL_NORMAL        wxFont(16, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID4_SWISS_NORMAL_NORMAL        wxFont(14, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL)
#define EGAV_FONT_MID4_SWISS_ITALIC_BOLD        wxFont(12, wxFONTFAMILY_SWISS, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_BOLD)


#define EGAV_FONT_DARKGRAY_COLOR				wxColor(92, 94, 96)
#define EGAV_FONT_BACK_LIGHT_GOLD_COLOR			wxColor(221, 194, 114)
#endif